name: proteina
channels:
  - nvidia
  - pytorch
  - conda-forge
  - pyg
  - bioconda
  - nodefaults
dependencies:
  - conda-forge::biotite=0.41.0
  - python=3.11
  - pip
  - pytorch=2.4.1
  - pyg::pyg=2.6.1
  - pyg::pytorch-sparse=0.6.18
  - pyg::pytorch-scatter=2.1.2
  - pyg::pytorch-cluster=1.6.3
  - conda-forge::transformers=4.48.3 # for ESMFold
  - bioconda::mmseqs2=17.b804f
  - pip:
    - python-dotenv==1.0.1
    - einops==0.6
    - dm-tree==0.1.8
    - lightning==2.5.0
    - loguru==0.7.2
    - hydra-core==1.3.1
    - numpy==1.23.5
    - pandas==1.5.3
    - biopandas==0.5.1
    - wandb==0.17.0
    - wget==3.2
    - tqdm==4.66.4
    - ml-collections==0.1.1
    - jaxtyping
    - cpdb-protein
    - loralib
    - biopython
